import type { Ticket, Asset, User, KBArticle, SLAPolicy, Branch, EngineerStats, ChartDataPoint, DashboardStats } from "./types";

export const mockUsers: User[] = [
  { id: "u0", name: "Bala",            email: "bala@nationalgroupindia.com",       role: "admin", department: "IT", branch: "India HQ",  isOnline: true },
  { id: "u1", name: "Sarah Mitchell", email: "s.mitchell@nationalgroupindia.com", role: "admin", department: "IT", branch: "London HQ", isOnline: true },
  { id: "u2", name: "James Chen", email: "j.chen@nationalgroupindia.com", role: "engineer", department: "IT", branch: "London HQ", isOnline: true },
  { id: "u3", name: "Priya Sharma", email: "p.sharma@nationalgroupindia.com", role: "engineer", department: "IT", branch: "London HQ", isOnline: false },
  { id: "u4", name: "Omar Al-Hassan", email: "o.hassan@nationalgroupindia.com", role: "engineer", department: "IT", branch: "Dubai Office", isOnline: true },
  { id: "u5", name: "Emma Thompson", email: "e.thompson@nationalgroupindia.com", role: "manager", department: "IT", branch: "London HQ", isOnline: true },
  { id: "u6", name: "David Park", email: "d.park@nationalgroupindia.com", role: "employee", department: "Finance", branch: "London HQ", isOnline: false },
  { id: "u7", name: "Aisha Okonkwo", email: "a.okonkwo@nationalgroupindia.com", role: "employee", department: "HR", branch: "Manchester", isOnline: true },
  { id: "u8", name: "Lucas Fernandez", email: "l.fernandez@nationalgroupindia.com", role: "employee", department: "Sales", branch: "Dubai Office", isOnline: true },
];

export const mockTickets: Ticket[] = [
  {
    id: "INC-10234",
    title: "Outlook not syncing emails after Windows update",
    description: "After the latest Windows 11 update pushed yesterday, my Outlook has stopped syncing new emails. It shows a connection error at the bottom right. I've already tried restarting Outlook and my computer.",
    status: "in_progress",
    priority: "high",
    category: "email",
    requesterId: "u6",
    requesterName: "David Park",
    requesterEmail: "d.park@nationalgroupindia.com",
    assignedToId: "u2",
    assignedToName: "James Chen",
    department: "Finance",
    branch: "London HQ",
    createdAt: "2026-07-29T08:15:00Z",
    updatedAt: "2026-07-29T10:30:00Z",
    dueAt: "2026-07-29T16:15:00Z",
    slaTier: "gold",
    slaBreached: false,
    tags: ["outlook", "windows-update", "email-sync"],
    comments: [
      { id: "c1", ticketId: "INC-10234", authorId: "u2", authorName: "James Chen", authorRole: "engineer", content: "Hi David, I can see the issue. The latest update changed an OAuth token registry key. I'll push a fix via Intune shortly.", isInternal: false, createdAt: "2026-07-29T09:00:00Z" },
      { id: "c2", ticketId: "INC-10234", authorId: "u2", authorName: "James Chen", authorRole: "engineer", content: "Intune policy deployed. Can you open Outlook and check if it prompts for sign-in?", isInternal: false, createdAt: "2026-07-29T10:30:00Z" },
    ],
    attachments: [{ id: "a1", name: "outlook-error.png", size: 245000, type: "image/png", url: "#", uploadedAt: "2026-07-29T08:20:00Z" }],
  },
  {
    id: "INC-10233",
    title: "Cannot connect to company VPN from home",
    description: "Getting error code 789 when trying to connect to the VPN. Was working fine last week. No changes on my end.",
    status: "open",
    priority: "critical",
    category: "vpn",
    requesterId: "u7",
    requesterName: "Aisha Okonkwo",
    requesterEmail: "a.okonkwo@nationalgroupindia.com",
    department: "HR",
    branch: "Manchester",
    createdAt: "2026-07-29T07:45:00Z",
    updatedAt: "2026-07-29T07:45:00Z",
    dueAt: "2026-07-29T11:45:00Z",
    slaTier: "gold",
    slaBreached: false,
    tags: ["vpn", "remote-access", "error-789"],
    comments: [],
    attachments: [],
  },
  {
    id: "INC-10232",
    title: "New MacBook Pro setup request – Sales team",
    description: "We have three new MacBook Pros arriving for the sales team this week. Need them enrolled in Intune, configured with standard software load, and Teams set up.",
    status: "pending",
    priority: "medium",
    category: "hardware",
    requesterId: "u5",
    requesterName: "Emma Thompson",
    requesterEmail: "e.thompson@nationalgroupindia.com",
    assignedToId: "u3",
    assignedToName: "Priya Sharma",
    department: "IT",
    branch: "London HQ",
    createdAt: "2026-07-28T14:00:00Z",
    updatedAt: "2026-07-29T09:00:00Z",
    dueAt: "2026-07-31T14:00:00Z",
    slaTier: "silver",
    slaBreached: false,
    tags: ["new-device", "macbook", "intune", "onboarding"],
    comments: [
      { id: "c3", ticketId: "INC-10232", authorId: "u3", authorName: "Priya Sharma", authorRole: "engineer", content: "Waiting on the devices to arrive from procurement. Will begin setup as soon as they're in.", isInternal: false, createdAt: "2026-07-29T09:00:00Z" },
    ],
    attachments: [],
  },
  {
    id: "INC-10231",
    title: "Printer on Floor 3 showing offline",
    description: "The Canon MX922 on the 3rd floor (near meeting room C) shows as offline in the printer queue but is physically powered on and showing no errors on its display.",
    status: "open",
    priority: "medium",
    category: "printer",
    requesterId: "u6",
    requesterName: "David Park",
    requesterEmail: "d.park@nationalgroupindia.com",
    department: "Finance",
    branch: "London HQ",
    createdAt: "2026-07-29T09:30:00Z",
    updatedAt: "2026-07-29T09:30:00Z",
    dueAt: "2026-07-30T09:30:00Z",
    slaTier: "bronze",
    slaBreached: false,
    tags: ["printer", "offline", "floor-3"],
    comments: [],
    attachments: [],
  },
  {
    id: "INC-10230",
    title: "Adobe Creative Cloud license not activating",
    description: "I was assigned an Adobe CC license last week but every time I open Photoshop it says my trial has expired. The IT ticket from license allocation says ID: LIC-8821.",
    status: "resolved",
    priority: "medium",
    category: "software",
    requesterId: "u8",
    requesterName: "Lucas Fernandez",
    requesterEmail: "l.fernandez@nationalgroupindia.com",
    assignedToId: "u4",
    assignedToName: "Omar Al-Hassan",
    department: "Sales",
    branch: "Dubai Office",
    createdAt: "2026-07-28T11:00:00Z",
    updatedAt: "2026-07-28T15:45:00Z",
    resolvedAt: "2026-07-28T15:45:00Z",
    dueAt: "2026-07-29T11:00:00Z",
    slaTier: "silver",
    slaBreached: false,
    tags: ["adobe", "license", "software"],
    comments: [
      { id: "c4", ticketId: "INC-10230", authorId: "u4", authorName: "Omar Al-Hassan", authorRole: "engineer", content: "Resolved - the license was assigned to your old email. Updated in Adobe Admin Console and re-sent the activation email.", isInternal: false, createdAt: "2026-07-28T15:45:00Z" },
    ],
    attachments: [],
  },
  {
    id: "INC-10229",
    title: "Laptop overheating and shutting down unexpectedly",
    description: "My Dell Latitude (Asset: DL-4421) keeps shutting down after about 20 minutes of use. The fan seems to be running at full speed before shutdown.",
    status: "in_progress",
    priority: "high",
    category: "hardware",
    requesterId: "u7",
    requesterName: "Aisha Okonkwo",
    requesterEmail: "a.okonkwo@nationalgroupindia.com",
    assignedToId: "u2",
    assignedToName: "James Chen",
    department: "HR",
    branch: "Manchester",
    createdAt: "2026-07-28T16:00:00Z",
    updatedAt: "2026-07-29T08:00:00Z",
    dueAt: "2026-07-29T08:00:00Z",
    slaTier: "gold",
    slaBreached: true,
    tags: ["laptop", "overheating", "dell", "hardware-fault"],
    comments: [],
    attachments: [],
  },
  {
    id: "INC-10228",
    title: "MFA prompts appearing every login – bypass needed",
    description: "Requesting temporary MFA bypass for the service account SVCACC-REPORT01 which is used for automated Power BI report generation. Currently breaking scheduled refreshes.",
    status: "pending",
    priority: "high",
    category: "security",
    requesterId: "u5",
    requesterName: "Emma Thompson",
    requesterEmail: "e.thompson@nationalgroupindia.com",
    assignedToId: "u1",
    assignedToName: "Sarah Mitchell",
    department: "IT",
    branch: "London HQ",
    createdAt: "2026-07-28T10:00:00Z",
    updatedAt: "2026-07-28T13:00:00Z",
    dueAt: "2026-07-29T10:00:00Z",
    slaTier: "gold",
    slaBreached: false,
    tags: ["mfa", "service-account", "security", "power-bi"],
    comments: [],
    attachments: [],
  },
  {
    id: "INC-10226",
    title: "Microsoft Teams crashing on startup after update",
    description: "Teams app is crashing immediately on launch since this morning. Error message: 'Teams.exe has stopped working'. Tried clearing cache, still crashing. Need Teams for a client call at 11am.",
    status: "in_progress",
    priority: "high",
    category: "software",
    requesterId: "u0",
    requesterName: "Bala",
    requesterEmail: "bala@nationalgroupindia.com",
    assignedToId: "u2",
    assignedToName: "James Chen",
    department: "IT",
    branch: "India HQ",
    createdAt: "2026-07-31T08:00:00Z",
    updatedAt: "2026-07-31T09:15:00Z",
    dueAt: "2026-07-31T16:00:00Z",
    slaTier: "gold",
    slaBreached: false,
    tags: ["teams", "crash", "software"],
    comments: [
      { id: "cb1", ticketId: "INC-10226", authorId: "u2", authorName: "James Chen", authorRole: "engineer", content: "Hi Bala, running a repair on the Teams installation via Intune. Should be fixed within 15 minutes.", isInternal: false, createdAt: "2026-07-31T09:15:00Z" },
    ],
    attachments: [],
  },
  {
    id: "INC-10225",
    title: "Unable to access SharePoint – permission denied",
    description: "Getting 'You need permission to access this site' when trying to open the NGI-Projects SharePoint. Was able to access it last week. No changes on my end.",
    status: "open",
    priority: "medium",
    category: "software",
    requesterId: "u0",
    requesterName: "Bala",
    requesterEmail: "bala@nationalgroupindia.com",
    department: "IT",
    branch: "India HQ",
    createdAt: "2026-07-30T14:30:00Z",
    updatedAt: "2026-07-30T14:30:00Z",
    dueAt: "2026-07-31T14:30:00Z",
    slaTier: "silver",
    slaBreached: false,
    tags: ["sharepoint", "permissions", "m365"],
    comments: [],
    attachments: [],
  },
  {
    id: "INC-10224",
    title: "New laptop setup – India HQ",
    description: "Requesting setup of new Dell Latitude 5550 for the India HQ office. Need Intune enrollment, M365 configuration, VPN client, and standard software stack.",
    status: "resolved",
    priority: "medium",
    category: "hardware",
    requesterId: "u0",
    requesterName: "Bala",
    requesterEmail: "bala@nationalgroupindia.com",
    assignedToId: "u4",
    assignedToName: "Omar Al-Hassan",
    department: "IT",
    branch: "India HQ",
    createdAt: "2026-07-28T09:00:00Z",
    updatedAt: "2026-07-29T16:00:00Z",
    resolvedAt: "2026-07-29T16:00:00Z",
    dueAt: "2026-07-30T09:00:00Z",
    slaTier: "silver",
    slaBreached: false,
    tags: ["new-device", "laptop", "intune", "setup"],
    comments: [
      { id: "cb2", ticketId: "INC-10224", authorId: "u4", authorName: "Omar Al-Hassan", authorRole: "engineer", content: "Device fully enrolled in Intune, all software deployed, VPN tested. Ready for collection from IT desk.", isInternal: false, createdAt: "2026-07-29T16:00:00Z" },
    ],
    attachments: [],
  },
  {
    id: "INC-10227",
    title: "Network shares inaccessible from Manchester branch",
    description: "All users in Manchester are unable to access the \\\\fileserver\\shared drive. Getting 'network path not found'. This has been going on since 7am.",
    status: "resolved",
    priority: "critical",
    category: "network",
    requesterId: "u7",
    requesterName: "Aisha Okonkwo",
    requesterEmail: "a.okonkwo@nationalgroupindia.com",
    assignedToId: "u1",
    assignedToName: "Sarah Mitchell",
    department: "HR",
    branch: "Manchester",
    createdAt: "2026-07-27T07:00:00Z",
    updatedAt: "2026-07-27T09:30:00Z",
    resolvedAt: "2026-07-27T09:30:00Z",
    dueAt: "2026-07-27T11:00:00Z",
    slaTier: "gold",
    slaBreached: false,
    tags: ["network", "file-share", "manchester", "outage"],
    comments: [],
    attachments: [],
  },
];

export const mockAssets: Asset[] = [
  { id: "a1", assetTag: "LPT-1021", name: "Dell Latitude 5540", type: "laptop", brand: "Dell", model: "Latitude 5540", serialNumber: "DLLAT5540-00112", status: "assigned", assignedToId: "u6", assignedToName: "David Park", department: "Finance", branch: "London HQ", location: "Floor 2, Desk 2A-14", purchaseDate: "2024-03-15", warrantyExpiry: "2027-03-14", purchasePrice: 1450, specs: "Intel i7-1365U, 16GB RAM, 512GB SSD", lastAuditDate: "2026-06-01" },
  { id: "a2", assetTag: "LPT-1022", name: "Dell Latitude 5540", type: "laptop", brand: "Dell", model: "Latitude 5540", serialNumber: "DLLAT5540-00113", status: "in_repair", branch: "Manchester", location: "IT Workshop", purchaseDate: "2024-03-15", warrantyExpiry: "2027-03-14", purchasePrice: 1450, lastAuditDate: "2026-06-01" },
  { id: "a3", assetTag: "LPT-1023", name: "MacBook Pro 14\"", type: "laptop", brand: "Apple", model: "MacBook Pro M3 Pro", serialNumber: "C02DT4MLMD6T", status: "in_stock", branch: "London HQ", location: "IT Storeroom", purchaseDate: "2026-07-20", warrantyExpiry: "2029-07-19", purchasePrice: 2499, lastAuditDate: "2026-07-20" },
  { id: "a4", assetTag: "LPT-1024", name: "MacBook Pro 14\"", type: "laptop", brand: "Apple", model: "MacBook Pro M3 Pro", serialNumber: "C02DT4MLMD6U", status: "in_stock", branch: "London HQ", location: "IT Storeroom", purchaseDate: "2026-07-20", warrantyExpiry: "2029-07-19", purchasePrice: 2499, lastAuditDate: "2026-07-20" },
  { id: "a5", assetTag: "LPT-1025", name: "MacBook Pro 14\"", type: "laptop", brand: "Apple", model: "MacBook Pro M3 Pro", serialNumber: "C02DT4MLMD6V", status: "in_stock", branch: "London HQ", location: "IT Storeroom", purchaseDate: "2026-07-20", warrantyExpiry: "2029-07-19", purchasePrice: 2499, lastAuditDate: "2026-07-20" },
  { id: "a6", assetTag: "DSK-0451", name: "Dell OptiPlex 7090", type: "desktop", brand: "Dell", model: "OptiPlex 7090", serialNumber: "DLO7090-99021", status: "assigned", assignedToId: "u7", assignedToName: "Aisha Okonkwo", department: "HR", branch: "Manchester", location: "Floor 1, Desk HR-07", purchaseDate: "2023-08-10", warrantyExpiry: "2026-08-09", purchasePrice: 1100, lastAuditDate: "2026-05-15" },
  { id: "a7", assetTag: "PRT-0112", name: "Canon imageRUNNER C3520i", type: "printer", brand: "Canon", model: "imageRUNNER C3520i", serialNumber: "CNIR3520-22410", status: "assigned", department: "All", branch: "London HQ", location: "Floor 3, Room C", purchaseDate: "2022-11-01", warrantyExpiry: "2025-10-31", purchasePrice: 3200, lastAuditDate: "2026-06-01" },
  { id: "a8", assetTag: "MON-0234", name: "Dell UltraSharp 27\"", type: "monitor", brand: "Dell", model: "U2722D", serialNumber: "DLMON2722-8821", status: "assigned", assignedToId: "u2", assignedToName: "James Chen", department: "IT", branch: "London HQ", location: "Floor 1, IT Bay", purchaseDate: "2024-01-10", warrantyExpiry: "2027-01-09", purchasePrice: 580, lastAuditDate: "2026-06-01" },
  { id: "a9", assetTag: "SWL-0055", name: "Microsoft 365 Business Premium", type: "software_license", brand: "Microsoft", model: "M365 Business Premium", serialNumber: "M365-BP-2024-55", status: "assigned", assignedToId: "u8", assignedToName: "Lucas Fernandez", department: "Sales", branch: "Dubai Office", location: "Cloud / Digital", purchaseDate: "2024-02-01", warrantyExpiry: "2027-01-31", purchasePrice: 264, lastAuditDate: "2026-07-01" },
  { id: "a10", assetTag: "SWL-0056", name: "Adobe Creative Cloud - 1 Year", type: "software_license", brand: "Adobe", model: "Creative Cloud All Apps", serialNumber: "ADO-CC-2025-0056", status: "assigned", assignedToId: "u8", assignedToName: "Lucas Fernandez", department: "Sales", branch: "Dubai Office", location: "Cloud / Digital", purchaseDate: "2025-07-28", warrantyExpiry: "2026-07-27", purchasePrice: 660, lastAuditDate: "2026-07-01" },
];

export const mockKBArticles: KBArticle[] = [
  { id: "kb1", title: "How to Reset Your Microsoft 365 Password", excerpt: "Step-by-step guide to resetting your M365 password using the self-service portal, including MFA setup.", category: "Account & Access", tags: ["password", "mfa", "m365", "self-service"], author: "Sarah Mitchell", views: 1842, helpful: 94, createdAt: "2025-01-10T10:00:00Z", updatedAt: "2026-06-15T10:00:00Z", featured: true },
  { id: "kb2", title: "Connecting to VPN: Setup Guide for Windows and Mac", excerpt: "Complete guide to installing and configuring the GlobalProtect VPN client on Windows 11 and macOS.", category: "Network & VPN", tags: ["vpn", "globalprotect", "remote-work", "windows", "macos"], author: "James Chen", views: 2341, helpful: 97, createdAt: "2025-02-05T10:00:00Z", updatedAt: "2026-07-10T10:00:00Z", featured: true },
  { id: "kb3", title: "Requesting Remote Assistance via Microsoft Teams", excerpt: "How to start a screen sharing session with the IT team directly from Teams for fast remote support.", category: "Remote Support", tags: ["teams", "remote", "screen-share", "quick-assist"], author: "Priya Sharma", views: 987, helpful: 91, createdAt: "2025-03-20T10:00:00Z", updatedAt: "2026-05-01T10:00:00Z", featured: true },
  { id: "kb4", title: "Enrolling a New Device in Microsoft Intune", excerpt: "How to enroll your company-issued or BYOD device in Intune to access company resources.", category: "Device Management", tags: ["intune", "mdm", "enroll", "byod"], author: "Omar Al-Hassan", views: 654, helpful: 88, createdAt: "2025-04-12T10:00:00Z", updatedAt: "2026-04-12T10:00:00Z", featured: false },
  { id: "kb5", title: "Outlook: Fixing Sync Issues After a Windows Update", excerpt: "Troubleshooting steps when Outlook stops syncing after a Windows update – covers token refresh and OAuth issues.", category: "Email & Outlook", tags: ["outlook", "sync", "windows-update", "oauth"], author: "James Chen", views: 1120, helpful: 92, createdAt: "2025-05-01T10:00:00Z", updatedAt: "2026-07-29T08:00:00Z", featured: false },
  { id: "kb6", title: "Setting Up Multi-Factor Authentication (MFA)", excerpt: "Configure MFA for your Microsoft account using the Authenticator app, SMS, or a hardware security key.", category: "Security", tags: ["mfa", "authenticator", "security", "2fa"], author: "Sarah Mitchell", views: 3102, helpful: 96, createdAt: "2024-12-01T10:00:00Z", updatedAt: "2026-03-01T10:00:00Z", featured: false },
  { id: "kb7", title: "Printer Troubleshooting: Common Issues & Fixes", excerpt: "Resolve the most common printer issues: offline status, paper jams, driver errors, and network connectivity.", category: "Hardware", tags: ["printer", "troubleshoot", "offline", "driver"], author: "Priya Sharma", views: 1567, helpful: 85, createdAt: "2025-06-10T10:00:00Z", updatedAt: "2026-06-10T10:00:00Z", featured: false },
  { id: "kb8", title: "How to Request a New Software License", excerpt: "Process for requesting commercial software licenses through the IT portal, including approval workflows.", category: "Software", tags: ["license", "software", "procurement", "request"], author: "Emma Thompson", views: 430, helpful: 82, createdAt: "2025-07-01T10:00:00Z", updatedAt: "2025-11-15T10:00:00Z", featured: false },
];

export const mockSLAPolicies: SLAPolicy[] = [
  { id: "s1", tier: "gold", priority: "critical", responseTimeHours: 1, resolutionTimeHours: 4, escalationTimeHours: 2 },
  { id: "s2", tier: "gold", priority: "high", responseTimeHours: 2, resolutionTimeHours: 8, escalationTimeHours: 4 },
  { id: "s3", tier: "gold", priority: "medium", responseTimeHours: 4, resolutionTimeHours: 24, escalationTimeHours: 12 },
  { id: "s4", tier: "gold", priority: "low", responseTimeHours: 8, resolutionTimeHours: 48, escalationTimeHours: 24 },
  { id: "s5", tier: "silver", priority: "critical", responseTimeHours: 2, resolutionTimeHours: 8, escalationTimeHours: 4 },
  { id: "s6", tier: "silver", priority: "high", responseTimeHours: 4, resolutionTimeHours: 24, escalationTimeHours: 8 },
  { id: "s7", tier: "silver", priority: "medium", responseTimeHours: 8, resolutionTimeHours: 48, escalationTimeHours: 24 },
  { id: "s8", tier: "silver", priority: "low", responseTimeHours: 24, resolutionTimeHours: 72, escalationTimeHours: 48 },
  { id: "s9", tier: "bronze", priority: "critical", responseTimeHours: 4, resolutionTimeHours: 24, escalationTimeHours: 8 },
  { id: "s10", tier: "bronze", priority: "high", responseTimeHours: 8, resolutionTimeHours: 48, escalationTimeHours: 24 },
  { id: "s11", tier: "bronze", priority: "medium", responseTimeHours: 24, resolutionTimeHours: 72, escalationTimeHours: 48 },
  { id: "s12", tier: "bronze", priority: "low", responseTimeHours: 48, resolutionTimeHours: 120, escalationTimeHours: 96 },
];

export const mockBranches: Branch[] = [
  { id: "b1", name: "London HQ", city: "London", country: "UK", headCount: 420, itEngineers: 8 },
  { id: "b2", name: "Manchester", city: "Manchester", country: "UK", headCount: 185, itEngineers: 3 },
  { id: "b3", name: "Dubai Office", city: "Dubai", country: "UAE", headCount: 92, itEngineers: 2 },
  { id: "b4", name: "Singapore", city: "Singapore", country: "SG", headCount: 67, itEngineers: 2 },
];

export const mockDashboardStats: DashboardStats = {
  totalOpen: 24,
  inProgress: 11,
  resolvedToday: 8,
  slaCompliance: 94.2,
  avgResolutionHours: 6.4,
  criticalOpen: 3,
  totalThisWeek: 67,
  assignedToMe: 5,
};

export const mockChartData: ChartDataPoint[] = [
  { date: "Mon", open: 8, resolved: 12, breached: 1 },
  { date: "Tue", open: 12, resolved: 9, breached: 0 },
  { date: "Wed", open: 15, resolved: 14, breached: 2 },
  { date: "Thu", open: 10, resolved: 16, breached: 1 },
  { date: "Fri", open: 14, resolved: 11, breached: 1 },
  { date: "Sat", open: 3, resolved: 5, breached: 0 },
  { date: "Sun", open: 2, resolved: 3, breached: 0 },
];

export const mockEngineerStats: EngineerStats[] = [
  { id: "u2", name: "James Chen", resolved: 142, avgTime: 5.2, slaCompliance: 97.2, rating: 4.8, open: 6 },
  { id: "u3", name: "Priya Sharma", resolved: 128, avgTime: 6.8, slaCompliance: 94.5, rating: 4.7, open: 4 },
  { id: "u4", name: "Omar Al-Hassan", resolved: 98, avgTime: 7.1, slaCompliance: 91.8, rating: 4.6, open: 3 },
  { id: "u1", name: "Sarah Mitchell", resolved: 56, avgTime: 4.1, slaCompliance: 98.2, rating: 4.9, open: 2 },
];
